timezone_dict = {
    "00": "Eniwetak, Kwajalein",
    "01": "Midway Island, Samoa",
    "02":"Hawaii",
    "03":"Alaska",
    "04":"Pacific Time (US & Canada)",
    "05":"Arizona",
    "06":"Mountain Time (US & Canada)",
    "07":"Central America",
    "08":"Central Time (US & Canada)",
    "09":"Mexico City",
    "10":"Saskatchewan",
    "11":"Bogota, Lima, Quito",
    "12":"Eastern Time (US & Canada)",
    "13":"Indiana (East)",
    "14":"Atlantic Time (Canada)",
    "15":"La Paz",
    "16":"Santiago",
    "17":"Newfoundland",
    "18":"Brasilia",
    "19":"Buenos Aires, Georgetown",
    "20":"Nuuk (Greenland)",
    "21":"Mid-Atlantic",
    "22":"Azores",
    "23":"Cape Verde Is",
    "24":"Casablanca, Monrovia",
    "25":"Dublin, Edinburgh, Lisbon, London",
    "26":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    "27":"Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    "28":"Brussels, Copenhagen, Madrid, Paris",
    "29":"Sarajevo, Skopje, Sofija, Vilnius, Warsaw, Zagreb",
    "30":"West Central Africa",
    "31":"Athens, Istanbul, Minsk",
    "32":"Bucharest",
    "33":"Cairo",
    "34":"Harare, Pretoria",
    "35":"Helsinki, Riga,Tallinn",
    "36":"Jerusalem",
    "37":"Baghdad",
    "38":"Kuwait, Riyadh",
    "39":"Moscow, St.Petersburg, Volgograd",
    "40":"Nairobi",
    "41":"Tehran",
    "42":"Abu Dhabi, Muscat",
    "43":"Baku",
    "44":"Kabul",
    "45":"Ekaterinburg",
    "46":"Islamabad, Karachi,Tashkent",
    "47":"Calcutta, Chennai, Mumbai, New Delhi",
    "48":"Kathmandu",
    "49":"Almaty, Novosibirsk",
    "50":"Astana, Dhaka",
    "51":"Sri Jayawardenapura",
    "52":"Rangoon",
    "53":"Bangkok, Hanoi, Jakarta",
    "54":"Krasnoyarsk",
    "55":"Beijing,ChongQing, HongKong,Urumqi",
    "56":"Irkutsk, Ulaanbaatar",
    "57":"Kuala Lumpur, Singapore",
    "58":"Perth",
    "59":"Taipei",
    "60":"Osaka, Sapporo, Tokyo, Seoul",
    "61":"Yakutsk",
    "62":"Adelaide",
    "63":"Darwin",
    "64":"Brisbane",
    "65":"Canberra, Melbourne, Sydney",
    "66":"Guam, Port Moresby",
    "67":"Hobart",
    "68":"Vladivostok",
    "69":"Magadan",
    "70":"Solomon Is., New Caledonia",
    "71":"Auckland, Wellington",
    "72":"Fiji, Kamchatka, Marshall Is",
    "73":"Nuku'alofa",
    "74":"Caracas",
    "75":"Namibia",
    "76":"Brazil-Acre)",
    "77":"Brazil-West",
    "78":"Brazil-East",
    "79":"Brazil-DeNoronha"
    }
